### PR TITLE
Implement abs, round for additional number types.

### PR DESCRIPTION
**Pull request by spellman**
abs did not work on:
  clojure.lang.Ratio
  clojure.lang.BigInt
  java.math.BigDecimal
  java.math.BigInteger
I defined defmethods for these classes, plus one for java.lang.Number to preserve the previous functionality for other number classes.

round did not work on
  clojure.lang.Ratio
  clojure.lang.BigInt
  java.math.BigDecimal
  java.math.BigInteger
  the various java integer classes (why shouldn't round work on integers?)
I defined defmethods to delegate java.Math.round for double and float, to act as the identity on the various integer classes, to delegate to java.math.BigDecimal#round for BigDecimal, and to cast Ratio to either a double or a BigDecimal and round it.

### CODE REVIEW

**Comment by seancorfield** [comment]
Can you open an issue for these things in JIRA for this project?

Per the CONTRIBUTING file, Clojure Contrib projects cannot accept Pull Requests:

https://github.com/clojure/algo.generic/blob/master/CONTRIBUTING.md

**Comment by spellman** [comment]
Done. Sorry about that.

**Comment by seancorfield** [comment]
No problem. Thanks for opening the issue on JIRA. Don't forget that for your patch to be considered, you need to sign and submit the Contributor's Agreement so all the legalities around your code are covered.

**Comment by spellman** [comment]
Yep - I did that and got a confirmation email, about an hour and a half ago, that it is signed and filed.

**Comment by seancorfield** [comment]
Cool! Welcome to the contributor club! Hopefully that'll get reviewed and approved quickly. Appreciate you taking the time to submit a patch!

**Comment by spellman** [comment]
Thanks! This is my first time to contribute to any project and I appreciate you and Konrad Hinsen (previously, over email) being so nice and helpful.

**Pull request closed without merging**
