### PR TITLE
Support for ISeq

### PR DESCRIPTION
**Pull request by mcohen01**
as referenced in http://dev.clojure.org/jira/browse/ALGOG-4

### CODE REVIEW

**Comment by sonntag** [comment]
Can someone merge this? We just ran into this issue again.

**Comment by jafingerhut** [comment]
@sonntag I am pretty sure this project doesn't accept pull requests for changes, rather using JIRA for tracking issues, patches, etc.  The JIRA issue for this is linked in the first comment above.  I would recommend adding a comment to that issue, perhaps linking to this issue, asking if anyone will work on it.

Konrad Hinsen is the original author for this project, but I do not know if he is still interested in updating it.  I can ask around to see if anyone else is interested in doing so -- perhaps Sean Corfield, who has taken over maintenance of some other Clojure projects.

**Comment by puredanger** [comment]
I can look at it.

**Comment by puredanger** [comment]
I didn't use this pr as the author is not a contributor but I have completed ALGOG-4 and released algo.generic as version 1.3 (will be available in Maven Central within the next hour probably).

**Pull request closed without merging**
